/*
 * generated by Xtext
 */
package com.frantz.txtuml;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TxtUMLRuntimeModule extends com.frantz.txtuml.AbstractTxtUMLRuntimeModule {

}
