/*
* generated by Xtext
*/
package com.frantz.txtuml;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TxtUMLStandaloneSetup extends TxtUMLStandaloneSetupGenerated{

	public static void doSetup() {
		new TxtUMLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

