/*
* generated by Xtext
*/
package com.frantz.drewio.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.frantz.drewio.services.DrewIOGrammarAccess;

public class DrewIOParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DrewIOGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.frantz.drewio.parser.antlr.internal.InternalDrewIOParser createParser(XtextTokenStream stream) {
		return new com.frantz.drewio.parser.antlr.internal.InternalDrewIOParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public DrewIOGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DrewIOGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
