/*
 * generated by Xtext
 */
package com.frantz.txtuml.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractTxtUMLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.frantz.txtuml.txtUML.TxtUMLPackage.eINSTANCE);
		return result;
	}
}
