/*
* generated by Xtext
*/
package com.frantz.drewio.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class DrewIOProposalProvider extends com.frantz.drewio.ui.contentassist.AbstractDrewIOProposalProvider {

}
