/*
 * generated by Xtext
 */
package com.frantz.drewio.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DrewIOUiModule extends com.frantz.drewio.ui.AbstractDrewIOUiModule {
	public DrewIOUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	
	
}
