/*
 * generated by Xtext
 */
package com.frantz.txtuml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TxtUMLUiModule extends com.frantz.txtuml.ui.AbstractTxtUMLUiModule {
	public TxtUMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
