/*
 * generated by Xtext
 */
package com.frantz.drewio;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DrewIORuntimeModule extends com.frantz.drewio.AbstractDrewIORuntimeModule {

}
