/*
 * generated by Xtext
 */
package com.frantz.txtuml.ui.contentassist

import com.frantz.txtuml.ui.contentassist.AbstractTxtUMLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TxtUMLProposalProvider extends AbstractTxtUMLProposalProvider {
}
