/*
* generated by Xtext
*/
package com.frantz.drewio.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DrewIOAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/frantz/drewio/parser/antlr/internal/InternalDrewIOParser.tokens");
	}
}
