/*
* generated by Xtext
*/
package com.frantz.txtuml.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TxtUMLAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/frantz/txtuml/parser/antlr/internal/InternalTxtUML.tokens");
	}
}
