/*
* generated by Xtext
*/
package com.frantz.txtuml.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.frantz.txtuml.services.TxtUMLGrammarAccess;

public class TxtUMLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TxtUMLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.frantz.txtuml.parser.antlr.internal.InternalTxtUMLParser createParser(XtextTokenStream stream) {
		return new com.frantz.txtuml.parser.antlr.internal.InternalTxtUMLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public TxtUMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TxtUMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
