/*
* generated by Xtext
*/
package com.frantz.txtuml;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TxtUMLUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.frantz.txtuml.ui.internal.TxtUMLActivator.getInstance().getInjector("com.frantz.txtuml.TxtUML");
	}
	
}
