/*
 * generated by Xtext
 */
package com.frantz.drewio.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.frantz.drewio.ui.internal.DrewIOActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DrewIOExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DrewIOActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DrewIOActivator.getInstance().getInjector(DrewIOActivator.COM_FRANTZ_DREWIO_DREWIO);
	}
	
}
